server:
  port: 8081

spring:
  rabbitmq:
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}

rabbitmq:
  queue: sensor.queue

properties:
  sensor:
    temperature-port: 3344
    humidity-port: 3355
    thresholds:
      t1: 35.0
      h1: 50.0